spring:
  datasource:
    username: u696489416_revee_dev_acc
    password: =Pg46BS>/
    url: jdbc:mysql://sql732.main-hosting.eu:3306/u696489416_revee_dev
  application:
    name: rev ee-backend
  main:
    banner-mode: off
  jpa:
    show-query: true
    show-sql: true
    hibernate:
      ddl-auto: update